/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mamu' at '2/13/18 3:04 PM' with Gradle 2.11
 *
 * @author mamu, @date 2/13/18 3:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
